import type { PlantRecord } from './model'

export const plants: PlantRecord = {
  'aloe-vera': {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis Miller',
    commonNames: ['Aloe', 'Burn Plant', 'First Aid Plant'],
    family: 'Asphodelaceae',
    description:
      'Aloe vera is a succulent, perennial, xerophytic plant.\n\t\t\tIt has turgid green leaves joined at the stem in a rosette pattern.\n\t\t\tThe leaves are up to 60 cm in length, lanceolate with serrated spine-like margins and an acute leaf apex. The leaves may produce a yellow, milky latex.',
  },
  astilbe: {
    id: 'astilbe',
    name: 'Astilbe',
    scientificName: 'Astilbe',
    commonNames: ['Astilbe'],
    family: 'Saxifragaceae',
    description: 'Astilbe is a perennial plant known for its feathery plumes of flowers. It is commonly used in shady gardens and woodland landscapes.',
  },
  bellflower: {
    id: 'bellflower',
    name: 'Bellflower',
    scientificName: 'Campanula',
    commonNames: ['Bellflower'],
    family: 'Campanulaceae',
    description:
      'Bellflower is a diverse genus of flowering plants known for their bell-shaped blooms. They come in various species and are valued for their ornamental qualities in gardens and landscapes.',
  },
  'black-eyed-susan': {
    id: 'black-eyed-susan',
    name: 'Black-Eyed Susan',
    scientificName: 'Rudbeckia hirta',
    commonNames: ['Black-Eyed Susan'],
    family: 'Asteraceae',
    description: 'Black-Eyed Susan is a cheerful, yellow-blooming perennial flower. It is a popular choice for gardens and attracts pollinators with its vibrant blooms.',
  },
  bougainvillea: {
    id: 'bougainvillea',
    name: 'Bougainvillea',
    scientificName: 'Bougainvillea',
    commonNames: ['Bougainvillea'],
    family: 'Nyctaginaceae',
    description: 'Bougainvillea is a tropical plant known for its vibrant, papery bracts that surround its small flowers.',
  },
  calendula: {
    id: 'calendula',
    name: 'Calendula',
    scientificName: 'Calendula officinalis',
    commonNames: ['Calendula', 'Pot Marigold'],
    family: 'Asteraceae',
    description: 'Calendula, also known as Pot Marigold, is a bright and cheerful annual or perennial flower with medicinal properties. It is often used in herbal remedies and skincare products.',
  },
  'california-poppy': {
    id: 'california-poppy',
    name: 'California Poppy',
    scientificName: 'Eschscholzia californica',
    commonNames: ['California Poppy'],
    family: 'Papaveraceae',
    description: 'California Poppy is a vibrant orange wildflower native to California. It is known for its drought tolerance and is often used in wildflower gardens.',
  },
  carnation: {
    id: 'carnation',
    name: 'Carnation',
    scientificName: 'Dianthus caryophyllus',
    commonNames: ['Carnation'],
    family: 'Caryophyllaceae',
    description: 'Carnation is a popular flowering plant with fringed petals. It is often used in floral arrangements and is associated with various cultural meanings.',
  },
  chrysanthemum: {
    id: 'chrysanthemum',
    name: 'Chrysanthemum',
    scientificName: 'Chrysanthemum',
    commonNames: ['Chrysanthemum'],
    family: 'Asteraceae',
    description: 'Chrysanthemums are popular ornamental flowers with various shapes and colors.',
  },
  'common-daisy': {
    id: 'common-daisy',
    name: 'Common Daisy',
    scientificName: 'Bellis perennis',
    commonNames: ['Common Daisy'],
    family: 'Asteraceae',
    description: 'Common Daisy is a small, white-petaled flower with a yellow center. It is a resilient plant that is often found in lawns and meadows.',
  },
  coreopsis: {
    id: 'coreopsis',
    name: 'Coreopsis',
    scientificName: 'Coreopsis',
    commonNames: ['Coreopsis', 'Tickseed'],
    family: 'Asteraceae',
    description: 'Coreopsis, commonly known as Tickseed, is a genus of flowering plants known for their bright and daisy-like blooms. They are popular in gardens and landscapes.',
  },
  daffodil: {
    id: 'daffodil',
    name: 'Daffodil',
    scientificName: 'Narcissus',
    commonNames: ['Daffodil'],
    family: 'Amaryllidaceae',
    description: 'Daffodil is a spring-flowering bulbous plant with trumpet-shaped flowers. It is widely cultivated for its bright and cheerful blooms.',
  },
  dahlia: {
    id: 'dahlia',
    name: 'Dahlia',
    scientificName: 'Dahlia',
    commonNames: ['Dahlia'],
    family: 'Asteraceae',
    description: 'Dahlias are prized for their diverse and colorful blooms, available in various shapes and sizes.',
  },
  dandelion: {
    id: 'dandelion',
    name: 'Dandelion',
    scientificName: 'Taraxacum officinale',
    commonNames: ['Dandelion'],
    family: 'Asteraceae',
    description: 'Dandelion is a common weed with distinctive yellow flowers. Despite being considered a weed, dandelions have culinary and medicinal uses.',
  },
  'golden-barrel-cactus': {
    id: 'golden-barrel-cactus',
    name: 'Golden Barrel Cactus',
    scientificName: 'Echinocactus grusonii',
    commonNames: ['Golden Barrel Cactus'],
    family: 'Cactaceae',
    description:
      'The Golden Barrel Cactus is a spherical cactus with a distinctive golden-yellow color.\n      It is covered in numerous sharp spines and is native to arid regions of Mexico.\n      This cactus is popular in xeriscape gardens and is well-suited to dry, desert environments.',
  },
  hibiscus: {
    id: 'hibiscus',
    name: 'Hibiscus',
    scientificName: 'Hibiscus',
    commonNames: ['Hibiscus'],
    family: 'Malvaceae',
    description: 'Hibiscus plants produce large, showy flowers and are commonly used in landscaping.',
  },
  iris: {
    id: 'iris',
    name: 'Iris',
    scientificName: 'Iris',
    commonNames: ['Iris'],
    family: 'Iridaceae',
    description: 'Iris is a genus of plants known for their distinctive, showy flowers. They come in various colors and are popular in gardens and floral arrangements.',
  },
  jasmine: {
    id: 'jasmine',
    name: 'Jasmine',
    scientificName: 'Jasminum',
    commonNames: ['Jasmine'],
    family: 'Oleaceae',
    description: 'Jasmine is a fragrant flowering plant often used in perfumery and teas.',
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    scientificName: 'Lavandula',
    commonNames: ['Lavandula angustifolia', 'L. vera'],
    family: 'Lamiaceae',
    description:
      'Lavender is a fragrant herb with narrow, aromatic leaves and spikes of violet-blue flowers.\n\t\tIt is known for its soothing fragrance and is commonly used in aromatherapy, perfumes, and culinary applications.',
  },
  lily: {
    id: 'lily',
    name: 'Lily',
    scientificName: 'Lilium',
    commonNames: ['Lily'],
    family: 'Liliaceae',
    description: 'Lilies are elegant flowers with distinctively shaped blooms and a pleasant fragrance.',
  },
  lotus: {
    id: 'lotus',
    name: 'Lotus',
    scientificName: 'Nelumbo nucifera',
    commonNames: ['Lotus'],
    family: 'Nelumbonaceae',
    description: 'Lotus plants have large, distinctive flowers and are associated with cultural and religious symbolism.',
  },
  magnolia: {
    id: 'magnolia',
    name: 'Magnolia',
    scientificName: 'Magnolia',
    commonNames: ['Magnolia'],
    family: 'Magnoliaceae',
    description: 'Magnolia is a genus of flowering trees and shrubs known for their large, fragrant flowers. They are often planted as ornamental trees in gardens and landscapes.',
  },
  marigold: {
    id: 'marigold',
    name: 'Marigold',
    scientificName: 'Tagetes',
    commonNames: ['Marigold'],
    family: 'Asteraceae',
    description: 'Marigold is a popular garden flower known for its bright and cheerful blooms.',
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    scientificName: 'Rosa rubiginosa',
    commonNames: ['Rose'],
    family: 'Rosaceae',
    description:
      'Roses are woody, perennial flowering plants with thorny stems.\n\t\tThey are known for their fragrant flowers, typically with five petals.\n\t\tRoses come in various colors and are widely cultivated for ornamental and symbolic purposes.',
  },
  'snake-plant': {
    id: 'snake-plant',
    name: 'Snake Plant',
    scientificName: 'Sansevieria trifasciata',
    commonNames: ["Mother-in-law's Tongue"],
    family: 'Asparagaceae',
    description:
      'The Snake Plant is a hardy, evergreen succulent with long, upright leaves.\n      Its leaves are typically green with variegated patterns.\n      Snake plants are known for their air-purifying qualities and adaptability to low light conditions.',
  },
  sunflower: {
    id: 'sunflower',
    name: 'Sunflower',
    scientificName: 'Helianthus annuus',
    commonNames: ['Sunflower'],
    family: 'Asteraceae',
    description: 'Sunflowers are known for their large, sun-like flower heads and edible seeds.',
  },
  tulip: {
    id: 'tulip',
    name: 'Tulip',
    scientificName: 'Tulipa',
    commonNames: ['Tulip'],
    family: 'Liliaceae',
    description: 'Tulip is a bulbous plant known for its showy, cup-shaped flowers. It is a popular spring-blooming flower in gardens and floral arrangements.',
  },
  'water-lily': {
    id: 'water-lily',
    name: 'Water Lily',
    scientificName: 'Nymphaea',
    commonNames: ['Water Lily'],
    family: 'Nymphaeaceae',
    description: 'Water Lily is an aquatic plant with floating leaves and vibrant flowers. It is often found in ponds and other water bodies, adding beauty to aquatic environments.',
  },
}
